- _includes/create_user.html
- _includes/nav/flask.html
- _includes/nav/home.html
- navigation/admin.md
- navigation/backend.md
- navigation/profile.md
The profile fetches data from database and puts in to sections.  For example, this is Thomas Edison. I still need to work on a lot of things for profile, like image fetching, updating, adding new sections for a user, etc. I updated the table for login so it fetches all the data now, and I updated the dropdown menu with flask home, profile, and create user.
> Make Frontend Cleaner & Basis for API Layer For Profile Setup

- _includes/create_user.html
- assets/js/api/config.js
- navigation/authentication/profile.md
- Got rid of Head/Body Tags for create_user.html
- Updated Profile.md to save photos in database for a user
- Checked if logout worked thanks to delete endpoint
-
> Profile Md

- navigation/authentication/profile.md
The save profile image works now, and there is no need for a reload thankfully :)
Sections data can be posted and fetched from the backend.
> Profile: Sections/Fix Profile Uploaf

- navigation/authentication/profile.md
Added attributes such as change name and change kasm_checkbox. Kasm-checkbox  has an additional step: fetches from backend (GET Request) to see if it is true or not. User can change whether it is checked or unchecked based on pressing the button
> Basic Setup For Profile

- navigation/authentication/profile.md
UID and Name are fetched from backend and added to the placeholder function (prefilled)
> Prefilled UID and Name

- _includes/nav/sass_basics.html
- _notebooks/Foundation/D-sass_basics/2024-07-20-SASS-hacks.ipynb
- _sass/minima/custom-styles.scss
- _sass/minima/nighthawk/hacks.scss
- created a new scss file for the showing of the completed hacks
- created a hacks ipynb for SASS
- added hacks to nav bar
> first iteration of SASS HACKS

- _sass/minima/nighthawk/chatbot.scss
WIP
replaced margin variables with auto margins or used spacing unit variable.
some button styling was being written for class instead of id, was fixed to be accurate to the HTML
> sass changes for ai chatbot

- _sass/minima/nighthawk/profile.scss
- navigation/authentication/profile.md
Used SASS and Font Awesome to replace buttons with icons
> change buttons to icons

- assets/js/api/profile.js
- navigation/authentication/login.md
- navigation/authentication/profile.md
Fix UI Changes. Will work on renaming directory soon.
> Fix UI Changes

- assets/js/api/profile.js
- navigation/authentication/profile.md
- Change/Put Password Succseuffly
- Redirect to Login Page
- Change
- Login
- Old Password Dosn't Work (401)
-New Password Succesufl Login
> profile.md, login

- navigation/authentication/analytics.md
> Github Analytics Fetch

- _includes/nav/Kasm_Sections/installer.html
- _includes/nav/Kasm_Sections/web_guides.html
- _includes/nav/kasm_cloud.html
- _notebooks/KASM/Config_Guides/2024-07-05-docker-cronjob-for-containers.ipynb
- _notebooks/KASM/Config_Guides/2024-07-05-manual-addition-of-docker-images.ipynb
- _notebooks/KASM/Config_Guides/2024-07-12-security-group-configuration.ipynb
- _notebooks/KASM/Config_Guides/2024-07-15-manual-registry-addition.ipynb
- _notebooks/KASM/Config_Guides/2024-07-15-persistent-data.ipynb
- _notebooks/KASM/Config_Guides/2024-07-30-autoscale-config.ipynb
- _notebooks/KASM/Config_Guides/2024-07-31-plans-for-big-meet.ipynb
- _notebooks/KASM/Config_Guides/2024-08-07-s3-persistent-storage-config.ipynb
- _posts/Kasm/Config_Guides/2024-07-12-terraform-vs-ansible.md
- _posts/Kasm/Installer_Guides/2024-07-12-multiserver-developers-guide.md
- _posts/Kasm/Installer_Guides/2024-07-12-multiserver-menu-guide.md
- navigation/section/kasm/guide.md
- navigation/section/kasm/installer.md
- scripts/md2ipynb.py
Made sure it was blogs in blogs.
> Move documentation for multiserver from kasmv2-frontend over to portfolio_2025

- _includes/nav/kasm_cloud.html
Dropdown in the submenu possibly ??
> dropdown in submenu test

- _includes/nav/kasm_cloud.html
- navigation/section/kasm.md
1. Reworked intro page to have system diagram (can click on this to enlarge), and removed some redundancy (still needs work) , also added a 'pitch' line 
2. Added a small menu with links on nav, can use for other links too these are temporary
> system diagram and essential links

- _sass/nighthawk/_main.scss
- _sass/nighthawk/login.scss
- navigation/authentication/login.md
- navigation/authentication/profile.md
Noticed some minor issues with signup and profile page. Here are my fixes:
- Add alert for updating uid, warning user that they will be logged out
-  Add alert for updating password,  warning user that they will be logged out
- Get rid of confusing, unneeded code (cleanup)
- Add SASS for signup button. Make sure it can't be clicked twice after signup. 
> **Alert For UID**
> **Alert For Password** 
> **Signup Button**
> Appropriate Changes to Sign Up/Profile

- scripts/verifyTools.sh
Add verify tools .sh script. Script verifies version/installation of required tools on the host it's run on and outputs all verification to a specified markdown file. Script can be used for debugging purposes, especially for issues related to software/tool versions.
> Add verify tools shell script

- _notebooks/CSA/2024-09-10-Unit7TeamteachPeriod3.ipynb
Unit 7 Team Teach for Period 3,
- Drishya
- Jason
- Tanuj
- Arnav
> pull request for Unit 7 Period 3

- _includes/nav/CSA_Units/csa_unit6_p1.html
- _notebooks/CSA/units_1_to_10/2024-09-12-unit_6.ipynb
- _notebooks/CSA/units_1_to_10/unit_06_p1/2024-09-12-unit_6-1.ipynb
- _notebooks/CSA/units_1_to_10/unit_06_p1/2024-09-12-unit_6-2.ipynb
- _notebooks/CSA/units_1_to_10/unit_06_p1/2024-09-12-unit_6-3.ipynb
- _notebooks/CSA/units_1_to_10/unit_06_p1/2024-09-12-unit_6-4.ipynb
- _notebooks/CSA/units_1_to_10/unit_06_p1/2024-09-12-unit_6-homepage.ipynb
Contributing all files required for the Unit 6 Team Teach created by period 1's group of Jonathan, Ian, Tarun, and Srijan.
> P1 Unit 6 Team Teach (Jonathan, Ian, Tarun, Srijan)

- _includes/nav/CSA_Units/csa_unit6.html
- _notebooks/CSA/units_1_to_10/unit_06/2024-09-13-Unit-6.1-Lesson.ipynb
- _notebooks/CSA/units_1_to_10/unit_06/2024-09-13-Unit-6.2-Lesson.ipynb
- _notebooks/CSA/units_1_to_10/unit_06/2024-09-16-Unit-6.3-Lesson.ipynb
- _notebooks/CSA/units_1_to_10/unit_06/2024-09-16-Unit-6.4-Lesson.ipynb
- _notebooks/CSA/units_1_to_10/unit_06/2024-09-18-Unit-6-Home-Page.ipynb
Welcome to Unit 6! In this unit, we will explore various concepts of **Arrays** in Java, focusing on traversing and manipulating arrays.
- Understand how to declare, initialize, and traverse arrays
- Learn how to manipulate array elements
- Practice writing algorithms that use arrays
1. Introduction to Arrays
2. Traversing Arrays
3. Array Algorithms
4. Searching and Sorting Arrays
> Unit 6 Team Teach Period 3- Nitin, Srini Akhil, Aditya

- _notebooks/CSA/units_1_to_10/unit_05/2024-09-17-unit_5-writing-methods.ipynb
- _notebooks/CSA/units_1_to_10/unit_05/2024-09-19-scope_access_example.ipynb
- _notebooks/CSA/units_1_to_10/unit_05/2024-09-scope_access_hacks.ipynb
Separating Scope and Access part of lesson for more organization and readability so the reader doesn't have to keep scrolling.
> Unit 5 Scope and Access Fix

- _notebooks/CSA/units_1_to_10/2024-09-18-Unit-8.ipynb
- Definition of 2D-Array terms
- How they are differnet from 1D-Arrays
- How to tranverse 2D-Arrays
- Row order
- Collegeboard
#Why we want to learn it first
We want to learn it first because we have always been used to using 1D-Arrays, and expanding our knowledge on 2D-Arrays would improve our Java knowledge overall. It also taught us how to use for-loops in java and how data structures in a dictionary and list in Java work. 
#How we will engage students
- Examples from collegeboard help make the learning process easier, images showing diagrams will help the students learn the process faster.
> Unit 8 2D Arrays Team Teach - Torin, Josh, David, Nandan

- _notebooks/CSA/units_1_to_10/unit_04_p1/2024-09-19-unit_4.1.ipynb
- _notebooks/CSA/units_1_to_10/unit_04_p1/2024-09-19-unit_4.2.ipynb
- _notebooks/CSA/units_1_to_10/unit_04_p1/2024-09-19-unit_4.3.ipynb
- _notebooks/CSA/units_1_to_10/unit_04_p1/2024-09-19-unit_4.4.ipynb
- _notebooks/CSA/units_1_to_10/unit_04_p1/2024-09-19-unit_4.ipynb
- _notebooks/CSA/units_1_to_10/unit_04_p1/2024-09-19-unit_4_quiz.ipynb
- _notebooks/CSA/units_1_to_10/unit_06/2024-09-18-Unit-6-Home-Page.ipynb
- Still missing nested loop iteration, will add in future.
> Unit 4 Team Teach

- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period3/foo.txt
> my first pull request

- _notebooks/CSA/units_1_to_10/unit_08/Period3/2024-09-18-8.2.ipynb
- _notebooks/CSA/units_1_to_10/unit_08/Period3/2024-09-19-8.1.ipynb
- _notebooks/CSA/units_1_to_10/unit_08/Period3/2024-09-19-Home.ipynb
- _notebooks/CSA/units_1_to_10/unit_08/Period3/2024-09-23-Unit8-ImageConverter.ipynb
- _notebooks/CSA/units_1_to_10/unit_08/Period3/2024-09-23-unit8-hw.ipynb
Accidentally forgot to put the 2D in our unit name and forgot to change week number.
> Final pull request

- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/2023-10-10-big-idea-3-5.ipynb
Shriya: Logical Operators and De Morgan's Law
Lalita: Relational Operators and Truth Table using Python 
Manas: Graphing Functions 
Ethan: Continuation of Graphing functions and Hacks
> boolean and mathmatical values

- _includes/nav/csp_units/csp_unit3_p2_fundamentals.html
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/2023-10-12-big-idea-3-8.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/2024-10-12-big-idea-3-8.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/2024-9-25-big-idea-3-8-1.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/2024-9-25-big-ideas-3-8-2.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/2024-9-25-big-ideas-3-8-3.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/2024-9-25-big-ideas-3-8-4.ipynb
We added a submenu so that each team member can make a lesson. We also added minor edits to the frontend.
> Pull request #1

- _includes/nav/csp_units/csp_bigIdea3_3.2_p1.html
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period1/3.2_BigIdeas/2024-01-24-3.2home.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period1/3.2_BigIdeas/2024-09-25-DT1.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period1/3.2_BigIdeas/2024-09-25-DT2.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period1/3.2_BigIdeas/2024-09-25-DT3.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period1/3.2_BigIdeas/2024-09-25-hacks.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period1/3.2_BigIdeas/2024-09-25-hw.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period1/3.2_BigIdeas/2024-09-25-json.ipynb
Team Member : Sonika Dhenuva Konda, Katherine Chen, Sanya Kapoor, Aditi Bandaru
Period 1, Mr Brown
Description: This is the Team Teach for 3.2 Big Ideas - Data Abstraction
> 3.2 Big Ideas, Period 1

- _includes/nav/csp_units/csp_unit3_p3_fundamentals.html
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period3/3_10_fundamentals/2024-10-25-fundamentals-3-10-1.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period3/3_10_fundamentals/2024-10-25-fundamentals-3-10-2.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period3/3_10_fundamentals/2024-10-25-fundamentals-3-10-3.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period3/3_10_fundamentals/2024-10-25-fundamentals-3-10-4.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period3/3_10_fundamentals/2024-10-25-fundamentals-3-10.ipynb
We  synced my repository in order to avoid a merge conflict. We also created a separate .html file for period 3, allowing our period to add their submenus and Jupyter Notebooks. We created a separate folder in period 3 for designated 3.10 files for organization. We will be pushing another pull request to get our notebooks with hacks and homework after this merge comes through.
> Pull Request for Period 3 (3.10)

- _includes/nav/csp_units/csp_bigIdea3_3.2_p1.html
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period1/3.2_BigIdeas/2024-01-24-3.2home.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period1/3.2_BigIdeas/2024-09-25-DT2.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period1/3.2_BigIdeas/2024-09-25-hw.ipynb
We added the quiz and the Grading Rubric to our Team Teach.
> new changes

- _includes/nav/csp_units/csp_unit3_p3_fundamentals.html
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period3/3_10_fundamentals/2024-10-25-fundamentals-3-10-1.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period3/3_10_fundamentals/2024-10-25-fundamentals-3-10-2.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period3/3_10_fundamentals/2024-10-25-fundamentals-3-10-3.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period3/3_10_fundamentals/2024-10-25-fundamentals-3-10-4.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period3/3_10_fundamentals/2024-10-25-fundamentals-3-10.ipynb
We are adding the period 3 submenu.
> adding period 3 html file and baseline

- _notebooks/CSA/units_1_to_10/unit_08/Period1/2024-09-12-U8-2D-Array-Algorithms-p1.ipynb
fixing/making final touches of 2D array team teach
> 2D array lesson

- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period4/2023-10-05-big-idea-3-2.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period4/2024-9-25-big-idea-3-2-1.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period4/2024-9-25-big-idea-3-2-Dictionaries.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period4/2024-9-25-big-idea-3-2-Float.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period4/2024-9-25-big-idea-3-2-Integers.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period4/2024-9-25-big-idea-3-2-List.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period4/2024-9-25-big-idea-3-2-None.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period4/2024-9-25-big-idea-3-2-Sets.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period4/2024-9-25-big-idea-3-2-Strings.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period4/2024-9-25-big-idea-3-2-Tuples.ipynb
3.2 Data abstraction: Thomas B, Collin G, Ian M, Aarush K
Integers
Floating-point
Strings
List
Tuples
Dictionaries
Sets
Booleans
None
> 3.2 lessons done

- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period5/nolan-y-jacob/2024-09-25-js-hw.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period5/nolan-y-jacob/2024-09-25-json.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period5/nolan-y-jacob/2024-09-25-variables.ipynb
uses justin's component, so it should work once justin's code gets merged.
> added submenu/links

- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period3/2024-10-25-fundamentals-3-10-4.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period3/2024-10-26-fundamentals-3-10-5.ipynb
I noticed that my grading notebook isn't displaying on the Nighthawk page, so I readded it. I also modified 3.10 permalinks to make sure they worked.
> Readding Grading 

- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period3/2024-09-23-fundamentals-3-1-1.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period3/2024-09-25-fundamentals-3-4-1.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period3/2024-09-27-fundamentals-3-1-2.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period3/2024-09-27-fundamentals-3-4-2.ipynb
> Big Idea 3.1-3.4 period 3

- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period2/2024-9-22-big-idea-3-2.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period2/2024-9-23-big-idea-3-2-6.ipynb
**Changes made:**
1. Add changes based on suggestions by peer reviewer in period 1 (Soni) - I specifically added serialization demonstration
2. Nikhil added an answer solution to Popcorn Hack 1 (because we only had answer keys for the other popcorn and homework hacks)
Changes were made based on peer review, as instructed by Mr. Mortensen. 
I have also completed peer reviewing the 3.2 group in period 3, [Utterance Comment](https://nighthawkcoders.github.io/portfolio_2025/csp/big-idea/p3/3-2-1)
Our group's planning and grading issues are located at: [GitHub Project](https://github.com/users/illuminati1618/projects/2/views/1)
Additional pull request may or may not be made based on additional suggestions by peer reviewer for a second time or by Mr. Mortensen (contact me on Slack if anything …
> Yash, Nikhil, Rohan, Neil - 3.2 Period 2 - Peer Review Pull Request

- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period1/3.2_BigIdeas/2024-09-25-DT1.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period1/3.2_BigIdeas/2024-09-25-DT2.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period1/3.2_BigIdeas/2024-09-25-DT3.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period1/3.2_BigIdeas/2024-09-25-hacks.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period1/3.2_BigIdeas/2024-09-25-hw.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period1/3.2_BigIdeas/2024-09-25-json.ipynb
Final additions to our Team Teach Big Ideas 3.2 (period 1)
> Final Touch-ups For P1, 3.2

- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period1/GMGZtable/2023-10-10-big-ideas-3-7-answer.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period1/GMGZtable/2023-10-11-big-idea-3-7.ipynb
reorganized
also added a new hack in 3.7
> Reorganization of 3.7 P.1

- _includes/nav/csp_units/csp_unit3_p1_fundamentals.html
> add 3.4 to nav

- _includes/nav/csp_units/csp_unit3_p2_fundamentals.html
The subsection topic is now included in submenu titles based on a suggestion by Mr. Mortensen.
> Request to update submenu titles to include topic of that subsection - Group 3.2 Period 2

- _includes/nav/csp_units/csp_unit3_p3_fundamentals.html
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period3/2024-09-25-fundamentals-3-4-3.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period3/2024-09-25-fundamentals-3-4-5.ipynb
Added submenu titles and revised JavaScript examples
> Minor Revisions (P3, 3.4)

- _includes/nav/csp_units/csp_unit3_p1_fundamentals.html
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period1/GMGZtable/2023-10-10-big-idea-3-6-hacks.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period1/GMGZtable/2023-10-10-big-idea-3-6-lesson.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period1/GMGZtable/2023-10-10-big-idea-3-6.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period1/GMGZtable/2023-10-10-big-idea-3-6_solution.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period1/GMGZtable/2023-10-10-big-ideas-3-7-answer.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period1/GMGZtable/2023-10-11-big-idea-3-7-hacks.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period1/GMGZtable/2023-10-11-big-idea-3-7-lesson.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period1/GMGZtable/2023-10-11-big-idea-3-7.ipynb
- added dropdown
- - consists of hacks
- - default lesson
- - hack solutions
- - only lesson
- also changed titles to be more explicit
> 3.6 and 3.7 Dropdown

- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period4/2024-09-25-big-idea-3-8-1.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period4/2024-09-25-big-idea-3-8-2.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period4/2024-09-25-big-idea-3-8-3.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period4/2024-09-25-big-idea-3-8-4.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period4/2024-09-26-big-idea-3-8-5.ipynb
I added authors to each of the pages as well as added more subheadings to each section of code to hopefully get the lessons ready for teaching.
> added authors and subtitles

- _includes/nav/csp_units/csp_unit3_p5_fundamentals.html
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period5/aaak/2024-09-23-3.1-objectives.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period5/aaak/2024-09-24-3.1.1-py.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period5/aaak/2024-09-24-3.1.2-py-hacks.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period5/aaak/2024-09-24-3.1.3-js.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period5/aaak/2024-09-24-3.4-A-objectives.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period5/aaak/2024-09-24-3.4-C1-js-strings.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period5/nolan-y-jacob/2024-09-25-js-hw.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period5/nolan-y-jacob/2024-09-25-json.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period5/nolan-y-jacob/2024-09-25-variables.ipynb
i committed kanhay's group's FIXED notebooks since he is having issues right now with branches. **i ran make myself and everything worked with no errors**
> p5: nolan's table added + kanhay's group fixed

- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period4/2024-09-25-big-idea-3-8-2.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period4/2024-09-25-big-idea-3-8-3.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period4/2024-09-25-big-idea-3-8-4.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period4/2024-09-26-big-idea-3-8-5.ipynb
Added unique elements to break monotony (coding memes at the end of lesson 3.8.2 and 3.8.5) and added hacks
> Final Changes

- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period5/nolan-y-jacob/2024-09-25-js-hw.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period5/nolan-y-jacob/2024-09-25-json.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period5/nolan-y-jacob/2024-09-25-variables.ipynb
> more popcorn + js notation + links fixed + description

- _includes/nav/csp_units/csp_unit3_p3_fundamentals.html
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period3/2024-10-03-fundamentals-3-10-5.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period3/2024-10-25-fundamentals-3-10-1.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period3/2024-10-25-fundamentals-3-10-2.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period3/2024-10-25-fundamentals-3-10-3.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period3/2024-10-25-fundamentals-3-10-4.ipynb
We changed our notebooks to match the period's agreed-upon theme. I also added borders (as per Xavier's request), and customized them to match the author of the page. For instance, a green border indicates the first author (but I kept it purple for my personal page since there was only one author). This allows our audience and graders to better understand who worked on what and who is sharing which part of the lesson. 
This is the updated repo after the bad pull request.
> Customizing Notebooks for 3.10

- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period3/2024-10-03-fundamentals-3-10-5.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period3/2024-10-25-fundamentals-3-10-1.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period3/2024-10-25-fundamentals-3-10-2.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period3/2024-10-25-fundamentals-3-10-3.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period3/2024-10-25-fundamentals-3-10-4.ipynb
I changed the files to make sure the markdown displayed correctly. I should've been more thorough modifying the files in the last pull request. I'm sorry for causing extra work for you, but thank you for letting me know!
> fixing pages (3.10, P3)

- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period3/2024-10-2-fundamentals-3.7.4.ipynb
> added 3.7.4

- _includes/nav/csp_units/csp_unit3_p4_fundamentals.html
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period4/2024-09-25-big-idea-3-6-1.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period4/2024-09-25-big-idea-3-6-2.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period4/2024-09-25-big-idea-3-6-3.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period4/2024-09-25-big-idea-3-6-4.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period4/2024-09-25-big-idea-3-7-1.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period4/2024-09-26-big-idea-3-7-2.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period4/2024-09-26-big-idea-3-7-3.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period4/2024-09-26-big-idea-3-7-4.ipynb
Titles included on dropdown and individual Jupyter notebooks
Added detailed lesson descriptions on each notebook
Fixed utterances
Changed the colors and added extra resources (unique elements)
> Fixed File Merge Issue + Utterances and Colors

- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period4/2024-09-25-big-idea-3-6-1.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period4/2024-09-25-big-idea-3-6-2.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period4/2024-09-25-big-idea-3-6-3.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period4/2024-09-25-big-idea-3-6-4.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period4/2024-09-25-big-idea-3-7-1.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period4/2024-09-26-big-idea-3-7-2.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period4/2024-09-26-big-idea-3-7-3.ipynb
- _notebooks/CSP/big-ideas/big-idea-3-part-1-fundamentals/Period4/2024-09-26-big-idea-3-7-4.ipynb
Files edited: 3.6.1-4 and 3.7.1-4 in Period 4
> Styling Formats Fixed

- _notebooks/CSSE/Lessons/Classes_and_Methods/2024-10-24-classes-intro.ipynb
- _notebooks/CSSE/Lessons/Classes_and_Methods/note.txt
Added Intro to JavaScript Classes & Methods to CSSE Lessons directory.
This can be found at `_notebooks/CSSE/Lessons/Classes_and_Methods/2024-10-24-classes-intro.ipynb`
> Added JavaScript Classes & Methods Intro

- _notebooks/CSSE/Lessons/Nested_Conditionals/2024-10-26-nested_conditionals.ipynb
Implemented a JSON object to manage ingredient availability and dynamically display messages based on user hunger state. The code checks for specific ingredients (bread, cheese, tomato) to determine if a meal can be prepared or if ordering food is necessary. Added console logging for debugging purposes and ensured proper DOM manipulation for displaying messages on the webpage.
> Added topic 2, popcorn hack 2, nested booleans conditional

- _notebooks/CSSE/Lessons/Classes_and_Methods/2024-10-27-classes-intro.ipynb
- _notebooks/CSSE/Lessons/Classes_and_Methods/2024-10-27-methods-in-depth.ipynb
Here's what what's changed:
- Updated Popcorn Hack 1 to JS Classes Intro (by me)
- Added JS Methods in Depth w/ Popcorn Hack 2 (by Alex)
:3
> Added to JavaScript Classes & Methods

- _notebooks/CSSE/Data_Abstraction_Lesson.ipynb
Add notebook for Data Abstraction
> Data Abstraction Notebook

- _notebooks/CSSE/Lessons/Strings/2024-10-30-strings-lesson-4-1.ipynb
fixes some problems with the notebooks.
> Some last minute fixes

- _notebooks/CSSE/Lessons/mathematic_expressions/impliment_in_rpg.ipynb
- _notebooks/CSSE/Lessons/mathematic_expressions/mathhomework.ipynb
- _notebooks/CSSE/Lessons/mathematic_expressions/operators.ipynb
Our final math_expressions lessons
> Mathematic Expressions

- _notebooks/CSSE/Lessons/Classes_and_Methods/2024-10-27-methods-in-depth.ipynb
- Fixed the syntax and descriptions under the `2024-10-27-methods-in-depth.ipynb` notebook (from Object-Literal to Class).
> Completed conversion from Object Literal to Class

- _notebooks/CSSE/Lessons/Nested_Conditionals/2024-10-26-nested_conditionals.ipynb
Refined instructions based on team feedback. Updated popcorn hack 2 in the file 2024-10-26-nested_conditionals.ipynb
> Refined instructions based on team feedback. Updated popcorn hack 2 in the file 2024-10-26-nested_conditionals.ipynb

- _notebooks/CSSE/Lessons/Classes_and_Methods/2024-10-27-classes-intro.ipynb
- _notebooks/CSSE/Lessons/Classes_and_Methods/2024-10-27-methods-in-depth.ipynb
- _notebooks/CSSE/Lessons/Classes_and_Methods/2024-11-04-classes-hw.ipynb
- _notebooks/CSSE/Lessons/Classes_and_Methods/2024-11-04-static-variables.ipynb
- Updated ALL JS Classes & Methods notebooks with front matters to display on site. These are all located under `/csse/javascript/fundamentals/classes/*`.
- Added Static Variables lesson written by Ethan Fu & reviewed by Lucas Masterson: `2024-11-04-static-variables.ipynb`.
- Added JS Classes & Methods Homework written by Lucas Masterson: `2024-11-04-classes-hw.ipynb`.
I suspect the homework might be a bit advanced (especially since we are skipping some lessons beforehand), but it should remain relatively trivial with a bit of research, which I suggested in the homework file. I introduced some new content:
- The `_` operator, which indicates that certain properties should remain _private_. This, however, is somewhat outdated (the `#` operator was introduced for full secrecy, but I think …
> Finished JS Classes & Methods Lesson

- _notebooks/CSSE/Lessons/Iteration/2024-11-5-iteration-3.ipynb
- _notebooks/CSSE/Lessons/Iteration/note.txt
pull request for CSSE iteration lesson
> iteration lesson

- _notebooks/CSSE/Lessons/Iteration/2024-11-2-Teach.ipynb
- _notebooks/CSSE/Lessons/Iteration/2024-11-2-homework.ipynb
- _notebooks/CSSE/Lessons/Iteration/2024-11-5-iteration-3.ipynb
> Iteration Lessons

- _notebooks/CSSE/Lessons/Data_Abstractions/2024-11-06-data_abstraction-homework.ipynb
- _notebooks/CSSE/Lessons/Data_Abstractions/2024-11-06-data_abstraction-p1.ipynb
- _notebooks/CSSE/Lessons/Data_Abstractions/2024-11-06-data_abstraction-popcornhacks.ipynb
> Add authors

- _notebooks/CSSE/Lessons/Mathematic_Expressions/2024-10-31-impliment_in_rpg.ipynb
- _notebooks/CSSE/Lessons/Mathematic_Expressions/2024-10-31-mathhomework.ipynb
- _notebooks/CSSE/Lessons/Mathematic_Expressions/2024-10-31-operators.ipynb
Adding names to lesson (mathematical_expressions)
> Author names on mathematical expressions lesson

- _notebooks/CSA/units_1_to_10/unit_03/Period1/2024-09-15-unit3_teamteach_3.3.ipynb
- _notebooks/CSA/units_1_to_10/unit_03/Period1/2024-09-15-unit3_teamteach_3.4.ipynb
Redid unit 3.3 and 3.4 for clarity and more engagement
> revisions for unit 3 team teach

- _notebooks/CSSE/Lessons/Booleans/2024-10-31-booleans-p2.ipynb
> Pull request teaching

- _includes/nav/kasm_cloud.html
> user guide

- assets/js/api/profile.js
> fix profile.js

- _includes/nav/homejava.html
- _includes/nav/kasm_cloud.html
- assets/js/api/login.js
- assets/js/api/profile.js
- navigation/authentication/logout.md
- navigation/authentication/profile.md
- navigation/authentication/signup.md
- navigation/kasm.md
- navigation/signup.md
Update all /login references to be /duallogin:
Files affected:
- _includes/nav/homejava.html
- _includes/nav/kasmcloud.html
- assets/js/api/login.js
- assets/js/api/profile.js
- navigation/authentication/logout.md
- navigation/authentication/profile.md
- navigation/authentication/signup.md
- navigation/kasm.md
- navigation/signup.md
> Ensure that login refers user to /duallogin 

- _includes/theme/cayman/base.html
- _includes/theme/dinky/base.html
- _includes/theme/midnight/base.html
- _includes/theme/time-machine/base.html
add login button to all themes.
> from CSP-Coders-2025

- _includes/nav/project/productivity-frontend/menu.html
- navigation/authentication/profilejava.md
Add display profile picture function again
> add display profile picture

- _notebooks/student_toolkit/BathroomPass/2024-12-17-statistics.ipynb
Added statistics notebook file back so the bathroom statistics can be viewed.
> Bathroom Statistics File Was Deleted

- _includes/nav/FRQ_teach/classesperiod3.html
- _notebooks/CSA/FRQ_teach/Classes/2025-01-10-ClassesFRQ_approach.ipynb
Just a navbar fix that I forgot to commit
> P1 Classes Team Teach Navbar Fix

- _notebooks/CSSE/Lessons/Iteration/2025-01-07-iterations.ipynb
- _notebooks/CSSE/Lessons/Iteration/2025-01-07-iterations2.ipynb
- _notebooks/CSSE/Lessons/Iteration/2025-01-07-iterations_hw.ipynb
- _notebooks/CSSE/Lessons/Iteration/2025-01-07-iterations_hw_answerkey.ipynb
- _notebooks/CSSE/Lessons/Iteration/2025-01-07-iterations_popcorn_hacks.ipynb
- _notebooks/CSSE/Lessons/Iteration/2025-01-07-iterations_popcorn_hacks_answerkey.ipynb
2025-01-07-iterations_hw is the Homework for the students practice so that they learn and develop their ideas about iterations
2025-01-07-iterations_hw_answerkey is the Answer key for the students so that when they finish the homework they can check if they got it right, or if not they would figure out what was wrong
2025-01-07-iterations_popcorn_hacks is the Popcorn hacks which they will do after the lesson
2025-01-07-iterations_popcorn_hacks_answerkey is the answer key so that they can check their answers
2025-01-07-iterations is the first lesson
2025-01-07-iterations is the second lesson
> Adding files

- _includes/MorteVision/head.html
- _includes/MorteVision/queuehead.html
- _posts/student_toolkit/ProductivityFrontend/mortevision/2025-01-17-Queue.html
- assets/MorteVision/js/SFU-Stream.js
- assets/MorteVision/js/SFU-View.js
- assets/MorteVision/js/queue.js
* fixed stupid errors
* changed all of this to ideally now be working with audioless connection
---------
> removed audio (#44)

- _notebooks/CSSE/Lessons/Nested_Conditionals/2025-01-08-NestedConditionals-Homework-tri2.ipynb
- _notebooks/CSSE/Lessons/Nested_Conditionals/2025-01-08-NestedConditionals-Lesson1-tri2.ipynb
- _notebooks/CSSE/Lessons/Nested_Conditionals/2025-01-08-NestedConditionals-Lesson2-tri2.ipynb
- _notebooks/CSSE/Lessons/Nested_Conditionals/2025-01-08-NestedConditionals-PopcornHack1-tri2.ipynb
- _notebooks/CSSE/Lessons/Nested_Conditionals/2025-01-08-NestedConditionals-PopcornHack2-tri2.ipynb
Files for the Nested Conditionals Lessons
1. Homework: Explains the objective and activity along with instructions on how to complete it.
2. Lesson 1: Goes over conditionals, introduces nested conditionals
3. Lesson 2: Shows how you can incorperate boolean into a nested conditional
4. Popcorn hack 1: Provides an activity to show nested conditionals in action
5. Popcorn hack 2: Shows how you can use true and false statements in nested conditionals
The lessons and popcorn hacks include DOM elements.
> Nested Conditionals Lesson Pull Request

- _posts/teacher_toolkit/Sagai/2024-10-21-Grader_Grader.md
- _posts/teacher_toolkit/StudentManagement/2024-11-04-table-details.md
- assets/MorteVision/style/queue.css
Only need a 1 line UI fix for review on Wednesday, see last commit.
> Minor UI Change for tomorrow

- _posts/gamify/Finance/stock/2024-10-26-stocksViewer.md
updating stocks viewer to javauri
> updating stocks viewer to javauri

- _posts/student_toolkit/assignments/2024-10-29-submissions.md
This reverts commit b3c619732dee1ae1af339cb884ac58cefb74d97d.
> Reapply "Student toolkit"

- _posts/student_toolkit/assignments/2024-10-29-submissions.md
FetchURI exists but now I need to add fetchoptions to confirm it works. It seems to be working.
> updating the submit page to use the fetchoptions stuff

- navigation/toolkit/student.md
pls dont change things if you dont know what they do. and for the love of all things holy PLEASE test your changes locally.
> HOTFIX APPLIED.

- _posts/student_toolkit/ProductivityFrontend/calendar/2024-12-16-calendar.md
editing and deleting events now works
also cleaned up some description stuff
> Calendar | Editing & Deleting

- _posts/student_toolkit/ProductivityFrontend/calendar/2024-12-16-calendar.md
Reverts nighthawkcoders/portfolio_2025#748
> Revert "Calendar | Editing & Deleting"

- _posts/gamify/Finance/crypto/2024-12-03-leaderboard.md
- _posts/gamify/Finance/stock/2024-10-24-stocksHome.md
Reverts nighthawkcoders/portfolio_2025#752
> Revert "stocks home UI fixes; leaderboard head tag removed"

- _posts/gamify/Finance/crypto/2024-12-03-leaderboard.md
- _posts/gamify/Finance/stock/2024-10-24-stocksHome.md
> Revert "stocks home UI fix; leaderboard head tag removed" (#113)

- _posts/gamify/Finance/crypto/2024-12-03-leaderboard.md
- _posts/gamify/Finance/stock/2024-10-24-stocksHome.md
* deleting useless head tag before i forget
* making table functional to show current crypto holdings
---------
Authored-by: Tanuj253 <tanujsai.real@gmail.com>
Authored-by: Drishya <modydrishya@gmail.com>
> Crypto (#129)

- _notebooks/CSSE/AdPlat_Game/Enemy_Collision_Handling/2025-03-24-HW_Enemy_Collision.ipynb
- _notebooks/CSSE/AdPlat_Game/Enemy_Collision_Handling/2025-03-24-Hacks_Overworld.ipynb
- _notebooks/CSSE/AdPlat_Game/Enemy_Collision_Handling/2025-03-24-Lesson1_Enemy_Collision.ipynb
- _notebooks/CSSE/AdPlat_Game/Enemy_Collision_Handling/2025-03-24-Lesson2_EnemyAnimations2.ipynb
Overworld Team Teach Led by Tanisha
Adding 4 files for our lesson.
- _Lesson 1_
- Render enemy characters (creepers) that move independently, consequence when there is a collision (Namira and Nico)
- _Lesson 2_
- Enemy animations (ex. explosion) (Hope)
Presentation
- Lesson 1 & 2 (Namira, Nico, Hope)
- Hacks (Shayanie, Paul)
- Homework (Yuna)
- Demo (Hope)
> Overworld Team Teach

- assets/js/adventureGame/GameLevelDesert.js
This adds a transition screen for when you go to the star wars level
> Transition screen

- _notebooks/student_toolkit/BathroomPass/2025-02-24-scanner.ipynb
- Removed toolkit layout from scanner --> scanner is its own separate page
> Fixed scanner

- navigation/authentication/analytics.md
- navigation/authentication/duallogin.md
- navigation/authentication/logout.md
- navigation/authentication/logoutjava.md
- navigation/authentication/signup.md
Reverts nighthawkcoders/portfolio_2025#854
> Revert "Trystan login profile analytics, clean up seemingly unused files (#170)"

- _posts/student_toolkit/ProductivityFrontend/calendar/2024-12-16-calendar.md
- navigation/authentication/logintoolkit.md
* period and type dropdown menus + styling
* changed period to classes + updated error messages
* added class based event filtering for CSA, CSP, and CSSE
* event saving in sqlite.db
* fixed error when adding first event
* Get rid of menu
* fix class filter
* fixed class differentiation
* removing bloat and making it less ugly
---------
> Calendar (#171)

- _posts/student_toolkit/TeamTeachToolkit/2025-04-04-TeamTeachToolkit_Signup.md
- navigation/authentication/analytics.md
* thymeleaf commit for analytics
* fixing bug where description is always set to test
* comments and formatting
* thymeleaf commit for analytics
* fixing bug where description is always set to test
* adding description feature
---------
> Team teach toolkit (#185)

- _layouts/fortunefinders.html
- _posts/gamify/2025-03-13-bankanalytics.md
- _posts/gamify/Finance/crypto/2024-12-03-investmentPortfolio.md
- assets/js/adventureGame/GameLevelAirport.js
* a little better?
* ?
* hard work
* key commit
* more edits
* sigma update
* changes
* changes
* revert back to showYellenModal
---------
> Bank branch frontend (#193)
